# Generated by Django 6.0.6 on 2026-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_patient_alcoholism_patient_diabetes_patient_handicap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='showed_up',
            field=models.BooleanField(default=True),
        ),
    ]
