# Generated by Django 6.0.6 on 2026-07-07 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='handicap',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['showed_up', 'sms_received'], name='appointment_showed__0e0534_idx'),
        ),
    ]
