# Generated by Django 6.0.6 on 2026-07-07 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='handicap',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
