# Generated by Django 6.0.6 on 2026-07-09 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_patient_handicap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='handicap',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['showed_up'], name='appointment_showed__9f86b7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['sms_received'], name='appointment_sms_rec_86bf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_day'], name='appointment_appoint_84ddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date_difference'], name='appointment_date_di_dfaad0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['age'], name='appointment_age_bbd5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='appointment_gender_145e53_idx'),
        ),
    ]
